name: Build and Deploy Disbot

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Test
        run: go test -v ./...
      - name: Set up docker build
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fattfatt/disbot:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and run docker via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/disbot
            git pull origin master
            cat << EOF > .env 
            DISBOTTOKEN=${{ secrets.DISBOTTOKEN }}
            DBNAME=${{ secrets.DBNAME }}
            DBUSERNAME=${{ secrets.DBUSERNAME }}
            DBPWD=${{ secrets.DBPWD }}
            REDDITUSERNAME=${{ secrets.REDDITUSERNAME }}
            REDDITPWD=${{ secrets.REDDITPWD }}
            REDDITCLIENTID=${{ secrets.REDDITCLIENTID }}
            REDDITCLIENTSECRET=${{ secrets.REDDITCLIENTSECRET }}
            REDDITREFRESHTOKEN=${{ secrets.REDDITREFRESHTOKEN }}
            REDDITACCESSTOKEN=${{ secrets.REDDITACCESSTOKEN }}
            EOF
            docker-compose pull
            docker-compose down
            docker-compose up -d
